### ISSUE TITLE
FR: Glass Pane: Please add -2/+2V and 0-2V, and also for 4V to the range menu

### ISSUE THREAD

**Issue by fractalgee** [patheros/PathSetModules#2]
Feature request for Glass Pane:

Please add -2/+2V and 0-2V, and also for 4V to the range menu, would be very useful avoiding more attenuverters than I already have in use in my patches.

**Comment by patheros** [comment]
So I added the ranges you asked for. You can get access to the pre-release builds here https://github.com/patheros/PathSetModules/releases/tag/2.2.0-db63f26

If you test them out, let me know if they work how you expected. Otherwise they should be in the library in the next month or so.

**Comment by fractalgee** [comment]
Super Duper and the speed of light! Awesome plugin just got even better. Apart from a unique sequencer this also makes for some funky stepped modulation source. Works as it should as far as quick testing showed, as I had a patch with 4 of them in it so super easy to throw in a scope and test
