### ISSUE TITLE
Request: manual scanning for CheeseGrater

### ISSUE THREAD

**Issue by MaZe6K** [patheros/PathSetModules#3]
Hi there!

I just got your Granular plugin and played a bit with CheeseGrater. 
Although I like it, I am a bit unhappy that it doesn't do what I thought it would do, and I hope you might be open to some suggestions to make it more powerful, maybe in a 2.0 or mkII version or something.

I would like to be able to scan the sample manually with a knob or CV, which I thought the "grain depth" knob was for... but CheeseGrater always just scans the sample at original speed.

I think it would be super nice if it had a control for scanning speed, with 0 in the middle position freezing the current position, and a modulation input that responds directly to relative position.

Since many people have asked for a granular sampler like that and you seem to be pretty close to it with this one, I hope that you might be motivated to move a bit further with it. :) (Optional swag points for adding a graphic that shows the sample position a la Morphagene.)

**Comment by patheros** [comment]
Thank you so much for purchasing my plugin!

Your idea sounds cool. Have you played around with Sifter? The Buffer Length and Buffer Start I think do what you are asking for. If you put a sample into it and lower the buffer length you can then use the buffer start to scan the sample. It also has a freeze feature.

I'd love to hear if that is what you are looking for. Maybe Sifter is enough for what you want? If not, I'd love to hear more about what that is lacking.

**Comment by MaZe6K** [comment]
Yes in Sifter it works how I want it with the buffer size, position and playback speed.

But now this one doesn't have pitch control and the recording of the buffer is more comfortable for me to do manually, like in CheeseGrater.
A combination of those two might be pretty perfect.

**Comment by MaZe6K** [comment]
I'll have to check again how exactly a Morphagene does it, but I think with those 5 controls plus pitch control and CV and a single stereo input with manual buffer recording this could be it - the often requested and longed for "Morphagene in Rack"

In the most ideal case there might be some basic position of those knobs that would make it react like a normal sampler, allowing to go from simple sample playback into grain cloud and back. Don't know if that would be technically possible or reaonable though.

**Comment by patheros** [comment]
For the clicking, i actually found a bug with Cheese Grater that will cause clicking whenever the Consistency is greater than 0. A fix for that is coming soon. I submitted 2.0.1 to the library.

**Comment by MaZe6K** [comment]
Thank You! Now I really like the sound of CheeseGrater!

Could you maybe just add the playback speed and buffer start controls to CheeseGrater then? Maybe just make the "Spread Rate" and "Slices of Toast" knobs in the smaller size and cram in a third row at the bottom for those 2 extra controls? That would be really cool!

2 more things I found: The "Spread Strength" knob could have a much bigger range to move into real chaos (maybe like 1 octave up and down), and in Sifter it seems to me that the feedback delay isn't doing anything.

**Comment by patheros** [comment]
Version 2.4.0 now has an expander for CheeseGrater that has this functionality. Enjoy!
